# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default='A Role!', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='description',
            field=models.CharField(default='A Setup!', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='setup',
            field=models.ManyToManyField(related_name='roles', through='mafia.SetupRole', to='mafia.Setup'),
        ),
    ]
