# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0002_auto_20170624_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='featuredSetup',
            field=models.BooleanField(default=False),
        ),
    ]
