# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0003_setup_featuredsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='action',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
