# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0005_auto_20170820_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='allignment',
            new_name='alignment',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='maximumPlayes',
            new_name='maximumPlayers',
        ),
    ]
