# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0006_auto_20170820_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='action',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
