# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allignment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('playerNumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SetupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.Role')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia.Setup')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='setup',
            field=models.ManyToManyField(through='mafia.SetupRole', to='mafia.Setup'),
        ),
    ]
