# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allignment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('playerNUmber', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='setup',
            field=models.ManyToManyField(to='mafia.Setup'),
        ),
    ]
