# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='playerNUmber',
            new_name='playerNumber',
        ),
    ]
